apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

# List all the resource YAMLs for node-exporter
resources:
  - deployment.yaml       # Deployment or DaemonSet manifest
  - service.yaml          # Service exposing node-exporter
  # - configmap.yaml      # optional, if you have ConfigMaps

# Optional: force all resources to default namespace
namespace: default

# Override the container image
images:
  - name: node-exporter            # Must match the 'name' in your container spec
    newName: sanjayyyy/node-exporter
    newTag: latest

